---
jobs:
- name: Deploy-app
  public: true
  serial: true
  plan:
  - get: simple-go-webapp
    trigger: true
  - task: run-tests
    file: simple-go-webapp/ci/tests.yml
  - put: deploy-web-app
    params:
      manifest: simple-go-webapp/manifest.yml
      path: simple-go-webapp/

resources:
- name: simple-go-webapp
  type: git
  source:
    uri: https://github.com/danhigham/simple-go-webapp.git

- name: deploy-web-app
  type: cf
  source:
    api: https://api.mvp2.cognizantone.org
    username: admin
    password: mvp2!23
    organization: foundryplatform
    space: cf_qa
    skip_cert_check: true 